### ISSUE TITLE
KSampler throw error: KeyError: 0

### ISSUE THREAD

**Issue by 1LucasGraham** [Kosinkadink/ComfyUI-Advanced-ControlNet#178]
![{2D97588B-34C5-4FD0-B570-6EA05A6C3DD5}](https://github.com/user-attachments/assets/efc7348b-bc5f-4663-b72c-39a96a98c9e2)

```
INFO - Prompt executed in 1.36 seconds
INFO - got prompt
INFO - loaded partially 157.14510064697265 157.14417266845703 0
ERROR - !!! Exception during processing !!! 0
ERROR - Traceback (most recent call last):
  File "D:\Tools\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Tools\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Tools\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Tools\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Tools\ComfyUI-aki-v1.3\nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\Tools\ComfyUI-aki-v1.3\nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\Tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\Tools\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 794, in sample_dpmpp_sde_gpu
    return sample_dpmpp_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, r=r)
  File "D:\Tools\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 612, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\Tools\ComfyUI-aki-v1.3\comfy\samplers.py", line 202, in calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "D:\Tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 468, in get_control_inject
    return self.get_control_advanced(x_noisy, t, cond, batched_number)
  File "D:\Tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 32, in get_control_advanced
    return self.sliding_get_control(x_noisy, t, cond, batched_number)
  File "D:\Tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 79, in sliding_get_control
    return self.control_merge(None, control, control_prev, output_dtype)
  File "D:\Tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 575, in control_merge_inject
    x = control_output[i]
KeyError: 0
```

need help!!!
workflows can be provided if needed.

thanks

**Comment by superhero-7** [comment]
Same problem！Did you solve it？
