### ISSUE TITLE
Ksampler issue, AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by 45uee** [Kosinkadink/ComfyUI-Advanced-ControlNet#201]
# ComfyUI Error Report
## Error Details
- **Node ID:** 316
- **Node Type:** KSampler
- **Exception Type:** TypeError
- **Exception Message:** AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given
## Stack Trace
```
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/drive/MyDrive/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/drive/MyDrive/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/drive/MyDrive/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1465, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1432, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 117, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 1020, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 918, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 904, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 873, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 857, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 714, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 861, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)

  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 764, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 384, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 839, in __call__
    return self.predict_noise(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 842, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 364, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 200, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)

  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 308, in _calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond), transformer_options)

```
## System Information
- **ComfyUI Version:** v0.3.6-8-gbf9a90a
- **Arguments:** main.py --dont-print-server
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA L4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 23802544128
  - **VRAM Free:** 11547672026
  - **Torch VRAM Total:** 12012486656
  - **Torch VRAM Free:** 33390042

## Logs
```
2024-12-03T18:30:31.469442 - [START] Security scan2024-12-03T18:30:31.469476 - 
2024-12-03T18:30:32.564926 - [DONE] Security scan2024-12-03T18:30:32.564960 - 
2024-12-03T18:30:33.545013 - ## ComfyUI-Manager: installing dependencies done.2024-12-03T18:30:33.545203 - 
2024-12-03T18:30:33.545298 - ** ComfyUI startup time:2024-12-03T18:30:33.545367 -  2024-12-03T18:30:33.545432 - 2024-12-03 18:30:33.5452212024-12-03T18:30:33.545493 - 
2024-12-03T18:30:33.545562 - ** Platform:2024-12-03T18:30:33.545622 -  2024-12-03T18:30:33.545680 - Linux2024-12-03T18:30:33.545743 - 
2024-12-03T18:30:33.545803 - ** Python version:2024-12-03T18:30:33.545861 -  2024-12-03T18:30:33.545919 - 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]2024-12-03T18:30:33.545976 - 
2024-12-03T18:30:33.546033 - ** Python executable:2024-12-03T18:30:33.546091 -  2024-12-03T18:30:33.546163 - /usr/bin/python32024-12-03T18:30:33.546221 - 
2024-12-03T18:30:33.546277 - ** ComfyUI Path:2024-12-03T18:30:33.546334 -  2024-12-03T18:30:33.546390 - /content/drive/MyDrive/ComfyUI2024-12-03T18:30:33.546448 - 
2024-12-03T18:30:33.546525 - ** Log path:2024-12-03T18:30:33.546586 -  2024-12-03T18:30:33.546643 - /content/drive/MyDrive/ComfyUI/comfyui.log2024-12-03T18:30:33.546700 - 
2024-12-03T18:30:33.562419 - 
Prestartup times for custom nodes:2024-12-03T18:30:33.562506 - 
2024-12-03T18:30:33.562588 -    0.9 seconds:2024-12-03T18:30:33.562654 -  2024-12-03T18:30:33.562715 - /content/drive/MyDrive/ComfyUI/custom_nodes/rgthree-comfy2024-12-03T18:30:33.562775 - 
2024-12-03T18:30:33.562838 -    6.6 seconds:2024-12-03T18:30:33.562896 -  2024-12-03T18:30:33.562956 - /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager2024-12-03T18:30:33.563015 - 
2024-12-03T18:30:33.563073 - 
2024-12-03T18:30:59.359073 - Total VRAM 22700 MB, total RAM 54233 MB
2024-12-03T18:30:59.359426 - pytorch version: 2.5.1+cu121
2024-12-03T18:30:59.362273 - WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.5.1+cu118 with CUDA 1108 (you have 2.5.1+cu121)
    Python  3.10.15 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-12-03T18:31:03.715837 - A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xformers/__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
2024-12-03T18:31:03.845016 - xformers version: 0.0.28.post3
2024-12-03T18:31:03.845433 - Set vram state to: NORMAL_VRAM
2024-12-03T18:31:03.845646 - Device: cuda:0 NVIDIA L4 : cudaMallocAsync
2024-12-03T18:31:17.206661 - Using pytorch cross attention
2024-12-03T18:32:32.685388 - [Prompt Server] web root: /content/drive/MyDrive/ComfyUI/web
2024-12-03T18:33:14.809085 - NumExpr defaulting to 12 threads.
2024-12-03T18:33:29.271808 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2024-12-03T18:33:29.272026 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-03T18:33:29.272180 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-03T18:34:14.211537 - /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2024-12-03T18:34:51.441251 - 
2024-12-03T18:34:51.441425 - [92m[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉[00m2024-12-03T18:34:51.441522 - 
2024-12-03T18:34:51.441593 - 
2024-12-03T18:34:59.071850 - ### Loading: ComfyUI-Manager (V2.51.8)2024-12-03T18:34:59.072017 - 
2024-12-03T18:35:41.734447 - ### ComfyUI Revision: 2884 [bf9a90a1] | Released on '2024-12-03'2024-12-03T18:35:41.734559 - 
2024-12-03T18:35:42.299642 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-03T18:35:42.299788 - 
2024-12-03T18:35:42.871047 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-03T18:35:42.871193 - 
2024-12-03T18:35:43.628366 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-03T18:35:43.628497 - 
2024-12-03T18:35:44.483984 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-03T18:35:44.484100 - 
2024-12-03T18:35:45.092398 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-03T18:35:45.092530 - 
2024-12-03T18:35:51.589424 - [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m2024-12-03T18:35:51.589561 - 
2024-12-03T18:35:51.589745 - [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `/content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m2024-12-03T18:35:51.589832 - 
2024-12-03T18:35:52.288394 - [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m218[0m [32mnodes successfully.[0m2024-12-03T18:35:52.288547 - 
2024-12-03T18:35:52.288668 - 
	[3m[93m"Every great dream begins with a dreamer."[0m[3m - Harriet Tubman[0m
2024-12-03T18:35:52.288761 - 
2024-12-03T18:36:23.790941 - here: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-tbox2024-12-03T18:36:23.791046 - 
2024-12-03T18:36:24.332062 - Using ckpts path: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotator2024-12-03T18:36:24.332223 - 
2024-12-03T18:36:24.332303 - Using symlinks: False2024-12-03T18:36:24.332367 - 
2024-12-03T18:36:24.332436 - Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']2024-12-03T18:36:24.332498 - 
2024-12-03T18:37:26.698489 - Total VRAM 22700 MB, total RAM 54233 MB
2024-12-03T18:37:26.698744 - pytorch version: 2.5.1+cu121
2024-12-03T18:37:26.698882 - xformers version: 0.0.28.post3
2024-12-03T18:37:26.699309 - Set vram state to: NORMAL_VRAM
2024-12-03T18:37:26.699559 - Device: cuda:0 NVIDIA L4 : cudaMallocAsync
2024-12-03T18:37:41.723824 - 
Import times for custom nodes:
2024-12-03T18:37:41.724182 -    0.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/websocket_image_save.py
2024-12-03T18:37:41.724334 -    1.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/masquerade-nodes-comfyui
2024-12-03T18:37:41.724442 -    1.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_ImageNormalization
2024-12-03T18:37:41.724548 -    1.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Segmentation
2024-12-03T18:37:41.724645 -    2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/Skimmed_CFG
2024-12-03T18:37:41.724736 -    2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/image-resize-comfyui
2024-12-03T18:37:41.724827 -    2.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Color_Transfer
2024-12-03T18:37:41.724921 -    3.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/prompt_injection
2024-12-03T18:37:41.725008 -    3.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sd-perturbed-attention
2024-12-03T18:37:41.725094 -    4.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-12-03T18:37:41.725220 -    4.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-inpaint-nodes
2024-12-03T18:37:41.725312 -    4.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-lama-remover
2024-12-03T18:37:41.725398 -    5.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_essentials
2024-12-03T18:37:41.725484 -    7.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-12-03T18:37:41.725572 -    9.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui
2024-12-03T18:37:41.725658 -   11.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-DepthAnythingV2
2024-12-03T18:37:41.725743 -   11.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyMath
2024-12-03T18:37:41.725835 -   11.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-12-03T18:37:41.725920 -   12.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
2024-12-03T18:37:41.726005 -   15.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
2024-12-03T18:37:41.726091 -   27.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/rgthree-comfy
2024-12-03T18:37:41.726204 -   31.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-tbox
2024-12-03T18:37:41.726295 -   45.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
2024-12-03T18:37:41.726392 -   51.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-12-03T18:37:41.726475 - 
2024-12-03T18:37:41.746536 - Starting server

2024-12-03T18:37:41.746988 - To see the GUI go to: http://127.0.0.1:8188
2024-12-03T18:40:43.804772 - FETCH DATA from: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-12-03T18:40:43.804835 - 2024-12-03T18:40:44.395551 -  [DONE]2024-12-03T18:40:44.395678 - 
2024-12-03T18:41:38.458336 - got prompt
2024-12-03T18:41:55.662201 - Using pytorch attention in VAE
2024-12-03T18:41:55.667988 - Using pytorch attention in VAE
2024-12-03T18:42:22.205452 - Requested to load AutoencoderKL
2024-12-03T18:42:22.259968 - loaded completely 9.5367431640625e+25 159.55708122253418 True
2024-12-03T18:45:02.900090 - model weight dtype torch.float16, manual cast: None
2024-12-03T18:45:02.917257 - model_type EPS
2024-12-03T18:45:29.029780 - Using pytorch attention in VAE
2024-12-03T18:45:29.031697 - Using pytorch attention in VAE
2024-12-03T18:45:29.999414 - Requested to load SDXLClipModel
2024-12-03T18:45:30.021075 - loaded completely 9.5367431640625e+25 1560.802734375 True
2024-12-03T18:47:17.181709 - [34mWAS Node Suite: [0m[33mBLIP Caption:[0m a cat sitting on top of a laptop computer[0m2024-12-03T18:47:17.181923 - 
2024-12-03T18:47:17.312190 - Requested to load ControlNet
2024-12-03T18:47:17.312493 - Requested to load SDXL
2024-12-03T18:47:17.949207 - loaded completely 9.5367431640625e+25 2386.120147705078 True
2024-12-03T18:47:19.553149 - loaded completely 9.5367431640625e+25 4897.0483474731445 True
2024-12-03T18:47:19.608650 - 
  0% 0/12 [00:00<?, ?it/s]2024-12-03T18:47:19.611217 - 
  0% 0/12 [00:00<?, ?it/s]2024-12-03T18:47:19.611338 - 
2024-12-03T18:47:19.624339 - !!! Exception during processing !!! AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given
2024-12-03T18:47:21.182519 - Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1465, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1432, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 117, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 1020, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 918, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 904, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 873, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 857, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 714, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 861, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 764, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 384, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 839, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 842, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 364, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 200, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 308, in _calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond), transformer_options)
TypeError: AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given

2024-12-03T18:47:21.184762 - Prompt executed in 342.46 seconds
2024-12-03T18:52:31.965520 - got prompt
2024-12-03T18:52:32.539229 - 
  0% 0/12 [00:00<?, ?it/s]2024-12-03T18:52:32.541530 - 
  0% 0/12 [00:00<?, ?it/s]2024-12-03T18:52:32.541647 - 
2024-12-03T18:52:32.546230 - !!! Exception during processing !!! AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given
2024-12-03T18:52:32.548099 - Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1465, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1432, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 117, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 1020, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 918, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 904, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 873, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 857, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 714, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 861, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 764, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 384, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 839, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 842, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 364, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 200, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "/content/drive/MyDrive/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 308, in _calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond), transformer_options)
TypeError: AdvancedControlBase.get_control_inject() takes 5 positional arguments but 6 were given

2024-12-03T18:52:32.550309 - Prompt executed in 0.31 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by 45uee** [comment]
Yes, that solved the problem, thank you

**Comment by Kosinkadink** [comment]
I created a PSA issue so that anyone in the future who experiences this will see an existing issue: https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/202

**Comment by wanderer99176** [comment]
我更新了Advanced-ControlNet还是没有解决，有其他办法吗？

**Comment by bluehood2022** [comment]
> 我更新了Advanced-ControlNet还是没有解决，有其他办法吗？
I've also updated the latest version, but the problem seems to persist
