### ISSUE TITLE
Help to install Kosinkadink/ComfyUI-AnimateDiff-Evolved AND Kosinkadink/ComfyUI-Advanced-ControlNet

### ISSUE THREAD

**Issue by gowthamjayaram** [Kosinkadink/ComfyUI-Advanced-ControlNet#204]
@Kosinkadink thx for these components.  I am installing them for comfyU on Mac M3 16GB and getting the following errors;

```
Traceback (most recent call last):
  File "/Users/gowww/ComfyUI/nodes.py", line 2036, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/__init__.py", line 4, in <module>
    from .animatediff.model_injection import prepare_dinklink_register_definitions
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_injection.py", line 17, in <module>
    from comfy.patcher_extension import CallbacksMP, WrappersMP, PatcherInjection
ModuleNotFoundError: No module named 'comfy.patcher_extension'
```

Server output:```

Import times for custom nodes:
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
```
Cannot find comfy.patcher_extension anywhere.    I have reinstalled all the Python libraries.  Thank you

**Comment by gowthamjayaram** [comment]
Adding the complete ComfyUI server output below:
```

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-04 12:34:49.567426
** Platform: Darwin
** Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ]
** Python executable: /Users/gowww/miniconda3/bin/python
** ComfyUI Path: /Users/gowww/ComfyUI
** Log path: /Users/gowww/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.7 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 18432 MB, total RAM 18432 MB
pytorch version: 2.5.1
Forcing FP16.
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: /Users/gowww/ComfyUI/web
### Loading: ComfyUI-Manager (V2.54)
### ComfyUI Revision: 2876 [8e4118c0] | Released on '2024-12-01'
xFormers not available
xFormers not available
Traceback (most recent call last):
  File "/Users/gowww/ComfyUI/nodes.py", line 2036, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/__init__.py", line 1, in <module>
    from .adv_control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes.py", line 3, in <module>
    from .nodes_main import (ControlNetLoaderAdvanced, DiffControlNetLoaderAdvanced,
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes_main.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet, is_sd3_advanced_controlnet
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 14, in <module>
    from .control_sparsectrl import SparseControlNet, SparseSettings, SparseConst, InterfaceAnimateDiffModel, create_sparse_modelpatcher, load_sparsectrl_motionmodel
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_sparsectrl.py", line 18, in <module>
    from comfy.patcher_extension import PatcherInjection
ModuleNotFoundError: No module named 'comfy.patcher_extension'

Cannot import /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet module for custom nodes: No module named 'comfy.patcher_extension'
Total VRAM 18432 MB, total RAM 18432 MB
pytorch version: 2.5.1
Forcing FP16.
Set vram state to: SHARED
Device: mps
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/gowww/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
DWPose: Onnxruntime with acceleration providers detected
Traceback (most recent call last):
  File "/Users/gowww/ComfyUI/nodes.py", line 2036, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/__init__.py", line 4, in <module>
    from .animatediff.model_injection import prepare_dinklink_register_definitions
  File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_injection.py", line 17, in <module>
    from comfy.patcher_extension import CallbacksMP, WrappersMP, PatcherInjection
ModuleNotFoundError: No module named 'comfy.patcher_extension'

Cannot import /Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved module for custom nodes: No module named 'comfy.patcher_extension'
NumExpr defaulting to 11 threads.
FizzleDorf Custom Nodes: Loaded
Web extensions folder found at /Users/gowww/ComfyUI/web/extensions/ComfyLiterals
here: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-tbox
Using ckpts path: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotator
Using symlinks: False
Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']

Import times for custom nodes:
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-sampler-lcm-alternative
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Latent-Modifiers
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-DepthAnythingV2
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.1 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-tbox
   0.1 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.1 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.2 seconds: /Users/gowww/ComfyUI/custom_nodes/comfyui_controlnet_aux

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
```

**Comment by Kosinkadink** [comment]
Your ComfyUI is outdated - if you update ComfyUI, you'll have comfy.patcher_extension file.
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/202

**Comment by MAXadobeX** [comment]
do you solve it?

> @Kosinkadink thx for these components. I am installing them for comfyU on Mac M3 16GB and getting the following errors;
> 
> ```
> Traceback (most recent call last):
>   File "/Users/gowww/ComfyUI/nodes.py", line 2036, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/__init__.py", line 4, in <module>
>     from .animatediff.model_injection import prepare_dinklink_register_definitions
>   File "/Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_injection.py", line 17, in <module>
>     from comfy.patcher_extension import CallbacksMP, WrappersMP, PatcherInjection
> ModuleNotFoundError: No module named 'comfy.patcher_extension'
> ```
> 
> Server output:```
> 
> Import times for custom nodes: 0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/ComfyLiterals 0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved 0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfyui-various 0.0 seconds: /Users/gowww/ComfyUI/custom_nodes/comfy-image-saver 0.0 seconds (IMPORT FAILED): /Users/gowww/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
> 
> ```
> Cannot find comfy.patcher_extension anywhere.    I have reinstalled all the Python libraries.  Thank you
> ```

**Comment by Kosinkadink** [comment]
@MAXadobeX just update ComfyUI.

**Comment by gowthamjayaram** [comment]
@Kosinkadink will do and revert. Thank you.  // @MAXadobeX

**Comment by gowthamjayaram** [comment]
Reinstalling ComfyUI worked.  thx @Kosinkadink // @MAXadobeX
