### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by olafchou** [Kosinkadink/ComfyUI-Advanced-ControlNet#205]
<img width="1182" alt="微信图片_20241205074528" src="https://github.com/user-attachments/assets/97de4964-2b09-46e6-b8f6-9e13dec6338b">
<img width="1150" alt="微信图片_20241205074544" src="https://github.com/user-attachments/assets/69023ae1-b3f5-4a6a-ac84-134c453ffb11">
<img width="540" alt="Snipaste_2024-12-05_07-46-09" src="https://github.com/user-attachments/assets/3eb376ee-9d7b-483a-a0d8-2836df77ffcb">

**Comment by Kosinkadink** [comment]
Check your console, likely your ComfyUI is outdated so the latest ACN doesn't work with it. Update ComfyUI and it'll work.

**Comment by MassiveTart** [comment]
I have the same error and the update did not fix it. It occurred after I installed a bunch of other custom nodes though so perhaps there is interreference?

**Comment by Kosinkadink** [comment]
That error isn't the actual error - can you check your console for the real detailed one and post it here? The Import Error just means there was an error while the nodes were starting up. Your issue is most likely that you need to update either ComfyUI or Advanced-ControlNet.

**Comment by MassiveTart** [comment]
When I attempt update all I get this error in the console:
 0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXTricks
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-composer

This is the startup log after I restart:
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 150, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1056, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

[Inspire Pack] IPAdapterPlus is not installed.
Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI_windows_portable\ComfyUI

This is the error popup I get when I restart:
Missing Node Types
When loading the graph, the following node types were not found

ACN_ReferencePreprocessor
ACN_ReferenceControlNetFinetune

Comfy UI manager:
(IMPORT FAILED) [ComfyUI-Advanced-ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet)
132
(IMPORT FAILED) [AnimateDiff Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved)
693
(IMPORT FAILED) [ComfyUI-LTXTricks](https://github.com/logtd/ComfyUI-LTXTricks)
Try fix
Uninstall
Nodes for scheduling ControlNet strength across timesteps and batched latents, as well as applying custom weights and attention masks.

**Comment by MassiveTart** [comment]
Sorry I think this is what you're after:

C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --highvram --fp32-vae --cuda-malloc --fast
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-06 09:37:38.737297
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\ComfyUI_windows_portable\ComfyUI
** Log path: C:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   8.7 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32594 MB
pytorch version: 2.5.1+cu124
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\ComfyUI_windows_portable\ComfyUI\web
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\blibla-comfyui-extensions\extensions
C:\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\__init__.py", line 1, in <module>
    from .adv_control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes.py", line 3, in <module>
    from .nodes_main import (ControlNetLoaderAdvanced, DiffControlNetLoaderAdvanced,
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_main.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet, is_sd3_advanced_controlnet
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 11, in <module>
    from comfy.controlnet import ControlBase, ControlNet, ControlNetSD35, ControlLora, T2IAdapter, StrengthType
ImportError: cannot import name 'ControlNetSD35' from 'comfy.controlnet' (C:\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py)

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet module for custom nodes: cannot import name 'ControlNetSD35' from 'comfy.controlnet' (C:\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py)
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\__init__.py", line 4, in <module>
    from .animatediff.model_injection import prepare_dinklink_register_definitions
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 17, in <module>
    from comfy.patcher_extension import CallbacksMP, WrappersMP, PatcherInjection
ModuleNotFoundError: No module named 'comfy.patcher_extension'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved module for custom nodes: No module named 'comfy.patcher_extension'
Adding C:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

**Comment by Kosinkadink** [comment]
Thanks! And in your case, your ComfyUI being outdated is the cause - both ADE and ACN can't find files for comfy that should exist. Update ComfyUI and your issues will go away.

**Comment by MassiveTart** [comment]
Thanks so much <3. I never expected such a quick response and to be so helpful. So it turns out the update comfy button in comfy UI manager doesn't work and I must run the custom update comfy script and it now my reference nodes are back where they should be. Appreciate very much, let me give the node a star
