### ISSUE TITLE
Type 'ControlNetPlusPlusAdvanced' requires a normal Image input, but received a proc_IMAGE input instead.

### ISSUE THREAD

**Issue by huongng105** [Kosinkadink/ComfyUI-Advanced-ControlNet#207]
<img width="1083" alt="Screenshot 2024-12-07 at 11 31 44" src="https://github.com/user-attachments/assets/7c5f11c4-bec7-4f31-8693-913c24b9cdfd">
<img width="934" alt="Screenshot 2024-12-07 at 11 32 40" src="https://github.com/user-attachments/assets/2334f25d-311e-4ea8-b366-fd0b54593e5a">
<img width="1728" alt="Screenshot 2024-12-07 at 11 33 03" src="https://github.com/user-attachments/assets/e9fe4a36-af1d-4154-9555-c3119f9b7945">
<img width="1076" alt="Screenshot 2024-12-07 at 11 36 21" src="https://github.com/user-attachments/assets/93b5b62d-4144-48ed-8ca0-a9734dfa324a">
# ComfyUI Error Report
## Error Details
- **Node ID:** 5828
- **Node Type:** ACN_AdvancedControlNetApply
- **Exception Type:** Exception
- **Exception Message:** Type 'ControlNetPlusPlusAdvanced' requires a normal Image input, but received a proc_IMAGE input instead.
## Stack Trace
```
  File "/content/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes_deprecated.py", line 304, in apply_controlnet
    new_positive, new_negative = AdvancedControlNetApply.apply_controlnet(self, positive=positive, negative=negative, control_net=control_net, image=image,

  File "/content/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes_main.py", line 134, in apply_controlnet
    raise Exception(f"Type '{type(c_net).__name__}' requires a normal Image input, but received a proc_IMAGE input instead.")

```
## System Information
- **ComfyUI Version:** v0.3.7-4-g93477f8
- **Arguments:** /content/ComfyUI/main.py --listen --port 8090
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15835660288
  - **VRAM Free:** 6480738944
  - **Torch VRAM Total:** 9059696640
  - **Torch VRAM Free:** 58145408

## Logs
```

2024-12-07T10:40:31.339326 - got prompt
2024-12-07T10:40:31.925450 - Failed to validate prompt for output 1197:
2024-12-07T10:40:31.925714 - * (prompt):
2024-12-07T10:40:31.925825 -   - Required input is missing: mask
2024-12-07T10:40:31.925947 - * MaskPreview+ 1197:
2024-12-07T10:40:31.926025 -   - Required input is missing: mask
2024-12-07T10:40:31.926115 - Output will be ignored
2024-12-07T10:40:31.927995 - Failed to validate prompt for output 1198:
2024-12-07T10:40:31.928166 - * (prompt):
2024-12-07T10:40:31.928251 -   - Required input is missing: mask
2024-12-07T10:40:31.928379 - * MaskPreview+ 1198:
2024-12-07T10:40:31.928453 -   - Required input is missing: mask
2024-12-07T10:40:31.928535 - Output will be ignored
2024-12-07T10:40:35.305844 - !!! Exception during processing !!! Type 'ControlNetPlusPlusAdvanced' requires a normal Image input, but received a proc_IMAGE input instead.
2024-12-07T10:40:35.306340 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes_deprecated.py", line 304, in apply_controlnet
    new_positive, new_negative = AdvancedControlNetApply.apply_controlnet(self, positive=positive, negative=negative, control_net=control_net, image=image,
  File "/content/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes_main.py", line 134, in apply_controlnet
    raise Exception(f"Type '{type(c_net).__name__}' requires a normal Image input, but received a proc_IMAGE input instead.")
Exception: Type 'ControlNetPlusPlusAdvanced' requires a normal Image input, but received a proc_IMAGE input instead.

2024-12-07T10:40:35.315672 - Prompt executed in 3.30 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

**Comment by Kosinkadink** [comment]
Thanks for the report. I think I've got a hunch about what the issue is, can you provide a screenshot of your Adv. ControlNet nodes in your workflow?

**Comment by huongng105** [comment]
> Thanks for the report. I think I've got a hunch about what the issue is, can you provide a screenshot of your Adv. ControlNet nodes in your workflow?
<img width="1689" alt="Screenshot 2024-12-07 at 11 54 44" src="https://github.com/user-attachments/assets/91ec6bb6-882d-4df4-883d-7f0c5f0a03e8">
<img width="1010" alt="Screenshot 2024-12-07 at 11 55 09" src="https://github.com/user-attachments/assets/3ba15225-28e0-402a-af8f-8f6a9ccf6283">
Thank you for your quick response! I’ve attached the requested screenshots of the Advanced ControlNet nodes in my workflow. Please let me know if there’s anything else you need to troubleshoot the issue.

**Comment by Kosinkadink** [comment]
I pushed out what I think is the fix for your issue - could you pull the latest version of Advanced-ControlNet and see if it works or you now?

**Comment by huongng105** [comment]
> I pushed out what I think is the fix for your issue - could you pull the latest version of Advanced-ControlNet and see if it works or you now?

Thank you so much for providing a quick solution to the issue! I’ve successfully resolved the problem after pulling the latest version of Advanced-ControlNet. I truly appreciate your help and dedication. Please keep up the amazing work—you’re doing an incredible job!

**Comment by Tedrer** [comment]
@Kosinkadink 

Hi,

Same im my workflow.
I have the latest version of Advanced-ControlNet.

Thanks!

> 
# ComfyUI Error Report
## Error Details
- **Node ID:** 459
- **Node Type:** ACN_AdvancedControlNetApply
- **Exception Type:** Exception
- **Exception Message:** Type 'SparseCtrlAdvanced' requires proc_IMAGE input via a corresponding preprocessor, but received a normal Image instead.
## Stack Trace
```
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advanced-controlnet\adv_control\nodes_deprecated.py", line 304, in apply_controlnet
    new_positive, new_negative = AdvancedControlNetApply.apply_controlnet(self, positive=positive, negative=negative, control_net=control_net, image=image,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advanced-controlnet\adv_control\nodes_main.py", line 131, in apply_controlnet
    raise Exception(f"Type '{type(c_net).__name__}' requires proc_IMAGE input via a corresponding preprocessor, but received a normal Image instead.")

```
## System Information
- **ComfyUI Version:** 0.3.10
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589410304
  - **VRAM Free:** 6533781834
  - **Torch VRAM Total:** 905969664
  - **Torch VRAM Free:** 30513482

## Logs
```
2025-01-14T21:26:54.882072 - [START] Security scan2025-01-14T21:26:54.882072 - 
2025-01-14T21:26:56.310966 - [DONE] Security scan2025-01-14T21:26:56.310966 - 
2025-01-14T21:26:56.316357 - [ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\HomePC\\Documents\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\user\\comfyui.log' -> 'C:\\Users\\HomePC\\Documents\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\user\\comfyui.prev.log'2025-01-14T21:26:56.316357 - 
2025-01-14T21:26:56.558593 - ## ComfyUI-Manager: installing dependencies done.2025-01-14T21:26:56.558593 - 
2025-01-14T21:26:56.558593 - ** ComfyUI startup time:2025-01-14T21:26:56.558593 -  2025-01-14T21:26:56.558593 - 2025-01-14 21:26:56.5582025-01-14T21:26:56.558593 - 
2025-01-14T21:26:56.559601 - ** Platform:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - Windows2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.559601 - ** Python version:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.559601 - ** Python executable:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.559601 - ** ComfyUI Path:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.559601 - ** User directory:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.559601 - ** ComfyUI-Manager config path:2025-01-14T21:26:56.559601 -  2025-01-14T21:26:56.559601 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-01-14T21:26:56.559601 - 
2025-01-14T21:26:56.560614 - ** Log path:2025-01-14T21:26:56.560614 -  2025-01-14T21:26:56.560614 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\comfyui.log2025-01-14T21:26:56.560614 - 
2025-01-14T21:26:58.364644 - 
Prestartup times for custom nodes:
2025-01-14T21:26:58.364644 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2025-01-14T21:26:58.364644 -    3.8 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2025-01-14T21:26:58.364644 - 
2025-01-14T21:27:05.161135 - Total VRAM 8192 MB, total RAM 32492 MB
2025-01-14T21:27:05.162166 - pytorch version: 2.5.1+cu124
2025-01-14T21:27:05.162166 - Set vram state to: NORMAL_VRAM
2025-01-14T21:27:05.163179 - Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
2025-01-14T21:27:08.187725 - Using pytorch attention
2025-01-14T21:27:21.787751 - [Prompt Server] web root: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2025-01-14T21:27:26.183197 - Total VRAM 8192 MB, total RAM 32492 MB
2025-01-14T21:27:26.183197 - pytorch version: 2.5.1+cu124
2025-01-14T21:27:26.185298 - Set vram state to: NORMAL_VRAM
2025-01-14T21:27:26.185298 - Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
2025-01-14T21:27:26.732823 - ### Loading: ComfyUI-Manager (V3.7.3)
2025-01-14T21:27:27.286392 - ### ComfyUI Version: v0.3.10-52-g1f1c7b7b | Released on '2025-01-13'
2025-01-14T21:27:28.147599 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-01-14T21:27:28.191160 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-01-14T21:27:28.575371 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-01-14T21:27:28.664889 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-01-14T21:27:28.880496 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-01-14T21:27:28.883521 - FETCH DATA from: https://api.comfy.org/nodes?page=1&limit=10002025-01-14T21:27:28.883521 - 2025-01-14T21:27:29.728877 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2025-01-14T21:27:29.729890 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2025-01-14T21:27:29.729890 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2025-01-14T21:27:32.003370 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2025-01-14T21:27:32.290107 - LOADED 6 FONTS2025-01-14T21:27:32.290107 - 
2025-01-14T21:27:32.410596 - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2025-01-14T21:27:34.034119 -  [DONE]2025-01-14T21:27:34.034119 - 
2025-01-14T21:27:34.424103 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes?page=1&limit=10002025-01-14T21:27:34.424103 - 
2025-01-14T21:27:35.024640 - nightly_channel: [4;94mhttps://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache[0m
2025-01-14T21:27:35.027991 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-01-14T21:27:35.027991 - 2025-01-14T21:27:35.438548 -  [DONE]2025-01-14T21:27:35.438548 - 
2025-01-14T21:27:41.661320 - 

███╗   ███╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗███████╗               
████╗ ████║██╔══██╗██╔════╝██║  ██║██║████╗  ██║██╔════╝               
██╔████╔██║███████║██║     ███████║██║██╔██╗ ██║█████╗                 
██║╚██╔╝██║██╔══██║██║     ██╔══██║██║██║╚██╗██║██╔══╝                 
██║ ╚═╝ ██║██║  ██║╚██████╗██║  ██║██║██║ ╚████║███████╗               
╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝               
                                                                       
██████╗ ███████╗██╗     ██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
██╔══██╗██╔════╝██║     ██║   ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
██║  ██║█████╗  ██║     ██║   ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
██║  ██║██╔══╝  ██║     ██║   ██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
██████╔╝███████╗███████╗╚██████╔╝███████║██║╚██████╔╝██║ ╚████║███████║
╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
                                                                       

2025-01-14T21:27:41.662493 - 
2025-01-14T21:27:42.310469 - [38;5;195m
🔊 Yvann Audio Reactive & Utils Node[38;5;222m : Loaded
[0m2025-01-14T21:27:42.310469 - 
2025-01-14T21:27:42.379414 - 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m2025-01-14T21:27:42.379414 - 
2025-01-14T21:27:42.514170 - 
2025-01-14T21:27:42.515191 - [92m[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉[00m2025-01-14T21:27:42.515191 - 
2025-01-14T21:27:42.515191 - 
2025-01-14T21:27:42.521414 - 
Import times for custom nodes:
2025-01-14T21:27:42.523662 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2025-01-14T21:27:42.523662 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\gcLatentTunnel.py
2025-01-14T21:27:42.523662 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2025-01-14T21:27:42.524775 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2025-01-14T21:27:42.525884 -    0.0 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
2025-01-14T21:27:42.525884 -    0.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advanced-controlnet
2025-01-14T21:27:42.525884 -    0.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2025-01-14T21:27:42.526989 -    0.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2025-01-14T21:27:42.527903 -    0.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2025-01-14T21:27:42.527903 -    0.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-evolved
2025-01-14T21:27:42.528903 -    0.2 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
2025-01-14T21:27:42.528903 -    0.6 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Yvann-Nodes
2025-01-14T21:27:42.528903 -    1.1 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2025-01-14T21:27:42.528903 -    1.4 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2025-01-14T21:27:42.528903 -    1.7 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2025-01-14T21:27:42.530412 -    2.4 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2025-01-14T21:27:42.530412 -    9.4 seconds: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
2025-01-14T21:27:42.530412 - 
2025-01-14T21:27:42.572749 - Starting server

2025-01-14T21:27:42.575117 - To see the GUI go to: http://127.0.0.1:8188
2025-01-14T21:27:45.514769 - FETCH DATA from: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-01-14T21:27:45.514769 - 2025-01-14T21:27:45.540940 -  [DONE]2025-01-14T21:27:45.540940 - 
2025-01-14T21:28:24.129410 - got prompt
2025-01-14T21:28:24.390162 - Using pytorch attention in VAE
2025-01-14T21:28:24.396552 - Using pytorch attention in VAE
2025-01-14T21:28:24.667957 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-01-14T21:28:26.044906 - model weight dtype torch.float16, manual cast: None
2025-01-14T21:28:26.058088 - model_type EPS
2025-01-14T21:28:27.322011 - Using pytorch attention in VAE
2025-01-14T21:28:27.326932 - Using pytorch attention in VAE
2025-01-14T21:28:27.731034 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-01-14T21:28:28.162121 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-01-14T21:28:29.431538 - Loading model from: C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\openunmix\umxl.pth2025-01-14T21:28:29.431538 - 
2025-01-14T21:28:29.958433 - Using cache found in C:\Users\HomePC/.cache\torch\hub\sigsep_open-unmix-pytorch_master
2025-01-14T21:28:31.579750 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Yvann-Nodes\nodes\audio\LoadAudioSeparationModel.py:49: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  separator.load_state_dict(torch.load(model_path, map_location='cpu'))
2025-01-14T21:28:33.766223 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-01-14T21:28:43.941735 - C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
2025-01-14T21:28:45.348375 - Requested to load AutoencoderKL
2025-01-14T21:28:46.345241 - loaded completely 9.5367431640625e+25 159.55708122253418 True
2025-01-14T21:29:01.112921 - Requested to load SD1ClipModel
2025-01-14T21:29:01.349168 - loaded completely 9.5367431640625e+25 235.84423828125 True
2025-01-14T21:29:02.019155 - !!! Exception during processing !!! Type 'SparseCtrlAdvanced' requires proc_IMAGE input via a corresponding preprocessor, but received a normal Image instead.
2025-01-14T21:29:02.101942 - Traceback (most recent call last):
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advanced-controlnet\adv_control\nodes_deprecated.py", line 304, in apply_controlnet
    new_positive, new_negative = AdvancedControlNetApply.apply_controlnet(self, positive=positive, negative=negative, control_net=control_net, image=image,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HomePC\Documents\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advanced-controlnet\adv_control\nodes_main.py", line 131, in apply_controlnet
    raise Exception(f"Type '{type(c_net).__name__}' requires proc_IMAGE input via a corresponding preprocessor, but received a normal Image instead.")
Exception: Type 'SparseCtrlAdvanced' requires proc_IMAGE input via a corresponding preprocessor, but received a normal Image instead.

2025-01-14T21:29:02.106139 - Prompt executed in 37.93 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

> 

![image](https://github.com/user-attachments/assets/e9be0ab2-f210-4821-a67f-7b5d1a3967b3)

**Comment by Kosinkadink** [comment]
@Tedrer if you're trying to use the sparse RGB model, you need to use the RGB SparseCtrl node to act as a preprocessor for the images. In the near future I'll allow unprocessed images to be input as well, but it will require some testing

**Comment by Tedrer** [comment]
@Kosinkadink Thanks for quick responce.

Thats not my workflow it is maked by yvann (https://www.youtube.com/watch?v=O2s6NseXlMc&list=PLBILrKhv-vidseEk0luBv87FCuhRR87KF&index=7). Suppost to work.
But, I see RGB preprocessor:
![image](https://github.com/user-attachments/assets/d0e411bc-6157-4ec1-a15f-2349a5d84c25)

**Comment by Tedrer** [comment]
![image](https://github.com/user-attachments/assets/8ccaa587-df20-4161-b8fd-949abfc0b0bd)
![image](https://github.com/user-attachments/assets/3ad62416-186a-495f-99de-28fec1d638eb)
Thanks

**Comment by Tedrer** [comment]
Right! It was wrong model... Thank you!
