### ISSUE TITLE
(IMPORT FAILED) ComfyUI-Advanced-ControlNet	Nodes

### ISSUE THREAD

**Issue by dinucci** [Kosinkadink/ComfyUI-Advanced-ControlNet#47]
Hello,

I'm having problems importing ComfyUI-Advanced-ControlNet Nodes

1	Kosinkadink	 (IMPORT FAILED) [ComfyUI-Advanced-ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet)	Nodes: ControlNetLoaderAdvanced, DiffControlNetLoaderAdvanced, ScaledSoftControlNetWeights, SoftControlNetWeights, CustomControlNetWeights, SoftT2IAdapterWeights, CustomT2IAdapterWeights

Both on Google Colab and my local ComfyUI on Linux install.

I tried disabling/enabling, uninstall/install.

Don't know what else to try

anyone has any idea on how to fix it?

**Comment by Kosinkadink** [comment]
Look in the console, it will have more info about why the node set couldn't be loaded, and post the full error stack here.

**Comment by dinucci** [comment]
It's working now, on both instances.

I didn't do anything different, strange thing.

thanks for the quick reply!

`### Loading: ComfyUI-Manager (V1.6.4)
**### ComfyUI Revision: 1788 [2db86b46] | Released on '2023-12-06'**
------------------------------------------
Comfyroll Studio v1.57 :  150 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Searge-SDXL v4.3.1 in /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL
### Loading: ComfyUI-Impact-Pack (V4.56.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
**Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!**`

**Comment by dinucci** [comment]
Thanks for the quick reply.

On my local Linux install it's working now, I didn't do anything different than before.

On Google Colab I still get the error, this is the output in the console after uninstall, restart and install again:


```shell
Install custom node 'ComfyUI-Advanced-ControlNet'
install: ['https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet']
Download: git clone 'https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet'
100% 246.0/246.0 [00:00<00:00, 284.95it/s]
Install: pip packages
Installation was successful.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
** ComfyUI start up time: 2024-01-02 19:47:42.551534

Prestartup times for custom nodes:
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 15102 MB, total RAM 52218 MB
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
2024-01-02 19:47:48.148923: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-02 19:47:48.148970: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-02 19:47:48.150277: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
### Loading: ComfyUI-Manager (V1.6.4)
### ComfyUI Revision: 1788 [2db86b46] | Released on '2023-12-06'
------------------------------------------
Comfyroll Studio v1.57 :  150 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Searge-SDXL v4.3.1 in /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL
### Loading: ComfyUI-Impact-Pack (V4.56.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 199 nodes successfully.

	"Don't be afraid to give up the good to go for the great." - John D. Rockefeller

Failed to auto update `Quality of Life Suit` 
QualityOfLifeSuit_Omar92_DIR: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
[tinyterraNodes] Loaded
Web extensions folder found at /content/drive/MyDrive/ComfyUI/web/extensions/ComfyLiterals
FizzleDorf Custom Nodes: Loaded
### Loading: ComfyUI-Inspire-Pack (V0.54.4)
Total VRAM 15102 MB, total RAM 52218 MB
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/__init__.py", line 1, in <module>
    from .control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/control/nodes.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/control/control.py", line 12, in <module>
    from .control_sparsectrl import SparseControlNet, SparseCtrlMotionWrapper, SparseMethod, SparseSettings, SparseSpreadMethod, PreprocSparseRGBWrapper
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/control/control_sparsectrl.py", line 30, in <module>
    from .utils import TimestepKeyframeGroup, disable_weight_init_clean_groupnorm, prepare_mask_batch
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/control/utils.py", line 228, in <module>
    class disable_weight_init_clean_groupnorm(comfy.ops.disable_weight_init):
AttributeError: module 'comfy.ops' has no attribute 'disable_weight_init'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet module for custom nodes: module 'comfy.ops' has no attribute 'disable_weight_init'

Import times for custom nodes:
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfy-plasma
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/As_ComfyUI_CustomNodes
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/wlsh_nodes
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.1 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   0.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL
   0.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   1.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui
   3.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
```

**Comment by Kosinkadink** [comment]
On your google collab, your ComfyUI is all the way from December 6th: ```### ComfyUI Revision: 1788 [2db86b46] | Released on '2023-12-06'```

If you update the ComfyUI version, your error will go away!

**Comment by dinucci** [comment]
You're right, I don't know why the script in colab doesn't update ComfyUI even though it says it does.

What I did was rename ComfyUI to ComfyUI2 in google drive, installed ComfyUI from scratch and then moved 'models' and 'custom_nodes' directories into the new one.

Kinda Frankesteinie but it worked :dagger: 

Many thanks!

**Comment by dinucci** [comment]
Solved
