### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'K:\ComfyUI\ComfyUI\temp\3dposeeditor\OpenPoseEditor_0_pose.png'

### ISSUE THREAD

**Issue by kakachiex2** [Kosinkadink/ComfyUI-Advanced-ControlNet#53]
![Screenshot 2024-01-14 114515](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/1762112/2e9a2e51-915f-474c-9a41-e5e669ac7b02)

**Comment by kakachiex2** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'K:\\ComfyUI\\ComfyUI\\temp\\3dposeeditor\\OpenPoseEditor_0_pose.png'

Prompt executed in 0.00 seconds
got prompt
2024-01-14 11:38:26,365 - root - ERROR - !!! Exception during processing !!!
2024-01-14 11:38:26,366 - root - ERROR - Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor\poseEditor3D_node.py", line 54, in output_pose
    i = Image.open(image_path)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\python_embeded\Lib\site-packages\PIL\Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'K:\\ComfyUI\\ComfyUI\\temp\\3dposeeditor\\OpenPoseEditor_0_pose.png'

Prompt executed in 0.01 seconds
got prompt
2024-01-14 11:44:58,043 - root - ERROR - !!! Exception during processing !!!
2024-01-14 11:44:58,044 - root - ERROR - Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor\poseEditor3D_node.py", line 54, in output_pose
    i = Image.open(image_path)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\python_embeded\Lib\site-packages\PIL\Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'K:\\ComfyUI\\ComfyUI\\temp\\3dposeeditor\\OpenPoseEditor_0_pose.png'

Prompt executed in 0.00 seconds

**Comment by kakachiex2** [comment]
Yesterday it was working but today I get this error.

**Comment by Kosinkadink** [comment]
I'm not a develop on the ComfyUI_3dPoseEditor nodes, so you'll need to open up an issue there instead!
